In [1]:
l = [0,1,2]

In [2]:
it = iter(l)

In [14]:
next(it)

2

In [15]:
next(it)

StopIteration: 

In [5]:
import numpy as np

In [6]:
x = 1

In [7]:
y = [1,2,3]

In [8]:
z = [[1,2],[3,4]]

In [11]:
np.repeat(x, 3)

array([1, 1, 1])

In [12]:
np.repeat(z, 2)

array([1, 1, 2, 2, 3, 3, 4, 4])

In [13]:
np.repeat(y,2)

array([1, 1, 2, 2, 3, 3])

In [16]:
import time

In [17]:
time.time()

1615942144.774705

In [18]:
time.time()

1615942156.0193958

In [19]:
time.time()

1615942171.4525588

In [20]:
time.time()

1615942302.1836104