In [1]:
l = [0,1,2]

In [2]:
it = iter(l)

In [3]:
next(it)

0

In [4]:
next(it)

1

In [5]:
import numpy as np

In [6]:
x = 1

In [7]:
y = [1,2,3]

In [8]:
z = [[1,2],[3,4]]

In [11]:
np.repeat(x, 3)

array([1, 1, 1])

In [12]:
np.repeat(z, 2)

array([1, 1, 2, 2, 3, 3, 4, 4])

In [13]:
np.repeat(y,2)

array([1, 1, 2, 2, 3, 3])